steps:

  # Download data from GCS into the build context
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', '-r', 'gs://deep-financial-research-data/data', '.']

  # Pull the previous image to use as cache
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'europe-west6-docker.pkg.dev/deep-financial-research/my-repo/my-app']
    allowFailure: true  # don't fail on first build when there's no cache yet

  # Build using the cached image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--cache-from', 'europe-west6-docker.pkg.dev/deep-financial-research/my-repo/my-app',
      '-t', 'europe-west6-docker.pkg.dev/deep-financial-research/my-repo/my-app',
      '.'
    ]


  # Push the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west6-docker.pkg.dev/deep-financial-research/my-repo/my-app']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'deep-financial-research'
      - '--image=europe-west6-docker.pkg.dev/deep-financial-research/my-repo/my-app'
      - '--region=europe-west6'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=1Gi'
      - '--set-secrets=OPENAI_API_KEY=OPENAI_API_KEY:latest,EDGAR_IDENTITY=EDGAR_IDENTITY:latest,DEEP_FINANCIAL_RESEARCH_PASSWORD=DEEP_FINANCIAL_RESEARCH_PASSWORD:latest'

options:
  logging: CLOUD_LOGGING_ONLY