"""S&P 500 company lookup utilities for query analysis."""

import json

from utils.config import settings
from utils.logging import logger


def _load_lookup() -> dict[str, dict]:
    """Loads the sp500_companies.json lookup generated by scripts/index.py."""
    path = settings.INDEX_DIR / "sp500_companies.json"
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        logger.warning("sp500_companies.json not found at %s — company detection disabled", path)
        return {}


_SP500_LOOKUP: dict[str, dict] = _load_lookup()


def find_sp500_mentions(query: str) -> list[str]:
    """Returns tickers for every S&P 500 company name found in the query.

    Args:
        query: The raw user question.

    Returns:
        List of matched tickers (e.g. ["ABNB"]). Empty if none found.
    """
    query_lower = query.lower()
    return [
        ticker
        for ticker, info in _SP500_LOOKUP.items()
        if info.get("company_name") and info["company_name"].lower() in query_lower
    ]
