"""S&P 500 company lookup utilities for query analysis."""

import json
import re
from difflib import get_close_matches

from utils.config import settings
from utils.logging import logger

# Words too short or too generic to be reliable company name signals
_STOP_WORDS = {
    "the", "and", "inc", "corp", "ltd", "co", "plc", "llc", "group",
    "company", "holdings", "class", "common", "share", "for", "are",
    "what", "how", "does", "its", "their", "this", "that", "with",
}


def _load_lookup() -> dict[str, dict]:
    """Loads the sp500_companies.json lookup generated by scripts/index.py."""
    path = settings.INDEX_DIR / "sp500_companies.json"
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        logger.warning("sp500_companies.json not found at %s — company detection disabled", path)
        return {}


def _load_aliases() -> dict[str, str]:
    """Loads the sp500_aliases.json lookup generated by scripts/generate_sp500_aliases.py."""
    path = settings.INDEX_DIR / "sp500_aliases.json"
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        logger.warning("sp500_aliases.json not found at %s — alias detection disabled", path)
        return {}


_SP500_LOOKUP: dict[str, dict] = _load_lookup()
_SP500_ALIASES: dict[str, str] = _load_aliases()

# Reverse index: significant words from company names → [(ticker, company_name)]
# Built once at module load for efficient fuzzy matching.
_NAME_WORD_TO_COMPANIES: dict[str, list[tuple[str, str]]] = {}
for _ticker, _info in _SP500_LOOKUP.items():
    _company_name = _info.get("company_name", "")
    if not _company_name:
        continue
    for _word in re.findall(r"[a-z]+", _company_name.lower()):
        if len(_word) >= 3 and _word not in _STOP_WORDS:
            _NAME_WORD_TO_COMPANIES.setdefault(_word, []).append((_ticker, _company_name))

_NAME_WORD_LIST: list[str] = list(_NAME_WORD_TO_COMPANIES.keys())


def find_sp500_candidates(query: str) -> list[tuple[str, str]]:
    """Returns (ticker, company_name) pairs where a significant query word appears in the name.

    Uses three matching strategies, merged and deduplicated:
    1. Word-level matching against legal company names in sp500_companies.json.
    2. Direct alias lookup against sp500_aliases.json (e.g. "google" → GOOGL).
    3. Fuzzy matching (difflib, cutoff=0.82) against company name words to catch typos.

    May return false positives — callers should verify with an LLM before acting on the result.

    Args:
        query: The raw user question.

    Returns:
        List of (ticker, company_name) candidates.
    """
    query_words = {
        token
        for token in re.findall(r"[a-z]+", query.lower())
        if len(token) >= 3 and token not in _STOP_WORDS
    }

    seen: set[str] = set()
    candidates: list[tuple[str, str]] = []

    # Strategy 1: word-level match against legal company names
    for ticker, info in _SP500_LOOKUP.items():
        company_name = info.get("company_name", "")
        if not company_name:
            continue
        if any(word in company_name.lower() for word in query_words):
            seen.add(ticker)
            candidates.append((ticker, company_name))

    # Strategy 2: alias lookup
    for word in query_words:
        ticker = _SP500_ALIASES.get(word)
        if ticker and ticker not in seen:
            company_name = _SP500_LOOKUP.get(ticker, {}).get("company_name", ticker)
            seen.add(ticker)
            candidates.append((ticker, company_name))

    # Strategy 3: fuzzy match query words against significant words in company names
    for word in query_words:
        matches = get_close_matches(word, _NAME_WORD_LIST, n=1, cutoff=0.82)
        for match in matches:
            for ticker, company_name in _NAME_WORD_TO_COMPANIES[match]:
                if ticker not in seen:
                    seen.add(ticker)
                    candidates.append((ticker, company_name))

    return candidates
