"""S&P 500 company lookup utilities for query analysis."""

import json

from utils.config import settings
from utils.logging import logger

# Words too short or too generic to be reliable company name signals
_STOP_WORDS = {
    "the", "and", "inc", "corp", "ltd", "co", "plc", "llc", "group",
    "company", "holdings", "class", "common", "share", "for", "are",
    "what", "how", "does", "its", "their", "this", "that", "with",
}


def _load_lookup() -> dict[str, dict]:
    """Loads the sp500_companies.json lookup generated by scripts/index.py."""
    path = settings.INDEX_DIR / "sp500_companies.json"
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        logger.warning("sp500_companies.json not found at %s — company detection disabled", path)
        return {}


_SP500_LOOKUP: dict[str, dict] = _load_lookup()


def find_sp500_candidates(query: str) -> list[tuple[str, str]]:
    """Returns (ticker, company_name) pairs where a significant query word appears in the name.

    Uses word-level matching so short references like "Meta" match "Meta Platforms, Inc."
    even though the full company name is not in the query. May return false positives —
    callers should verify with an LLM before acting on the result.

    Args:
        query: The raw user question.

    Returns:
        List of (ticker, company_name) candidates.
    """
    query_words = {
        word.lower().strip(".,?!'\"")
        for word in query.split()
        if len(word) >= 3 and word.lower().strip(".,?!'\"") not in _STOP_WORDS
    }

    candidates = []
    for ticker, info in _SP500_LOOKUP.items():
        company_name = info.get("company_name", "")
        if not company_name:
            continue
        name_lower = company_name.lower()
        if any(word in name_lower for word in query_words):
            candidates.append((ticker, company_name))

    return candidates
